### PR TITLE
 Apollo server replaced with cultofcoders packages: apollo and meteor-apollo-accounts for easy subscriptions and meteor-accounts for graphql

### PR DESCRIPTION
**Pull request by ajaybhatia**

### CODE REVIEW

**Comment by maka-io** [comment]
👍 You're awesome Ajay, thanks!

**Comment by ajaybhatia** [comment]
My pleasure, Matt!

**Comment by maka-io** [comment]
@ajaybhatia Hey, so I saw there was a strange register for the API (trying to import the rest API file but was never created) so I just made a small fix to that.  If you update this branch and sort out the "withApollo" thing I'll get it pushed right out.

**Comment by maka-io** [comment]
@ajaybhatia wait, that wasn't a problem with this PR, it was a separate issue!  Sorry for the confusion.  If you submit the PR again, I'll fix the problem on my end and we'll be square (ish).

**Comment by ajaybhatia** [comment]
Oh I see! Actually I tested the code with react-apollo-hooks rather than withApollo and everything works fine. I'm more in habit of using hooks now and my almost all components are now functional components. But nice you've found the issue and fixed it! 

It's almost midnight here.

**Comment by ajaybhatia** [comment]
I think the only thing left is SSR with Apollo. I hardly used SSR with Apollo in any of project. But I'll try to replace the outdated SSR code with newer one soon.

**Comment by maka-io** [comment]
I wouldn't worry about SSR with Apollo, I can take a look at that if you don't want to go down that path.

**Comment by maka-io** [comment]
if you just want to make the PR, I can sort out the other stuff.  Or wait till the morning! Either way, thank you for your help, and sorry for the confusion.

**Pull request merged**
